spring:
  application:
    name: api-gateway

#    GATEWAY CONFIGURATION

  cloud:
      gateway:
         routes:
           - id : User_Service
             uri: http://localhost:8081/user_service
             predicates:
               - Path=/user_service/**
             filters:
               - StripPrefix=1

#
#                      service 2
           - id : service2
             uri: http://localhost:9001/service2
             predicates:
               - Path=/service2/**
             filters:
             - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_URI:http://localhost:8761/eureka/}